# Site settings
title: Sam Hutchings | Artist and Designer
description: >- # this means to ignore newlines until "baseurl:"
  Holistic Designer and Artist on a mission to create a better world. Believer in Design Thinking.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://wwww.samhutchings.co" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU


# Build settings
remote_theme: YoussefRaafatNasry/portfolYOU
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Sam Hutchings
  image    : https://pbs.twimg.com/profile_images/1095437940442972160/ykDY_uZC_400x400.jpg
  email    : hi@samhutchings.co
  github   : Smutchings
  twitter  : Smutchings
  linkedin : Smutchings
  # facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock