# Site settings
title: Sam Hutchings
email: hi@samhutchings.co
description: > # this means to ignore newlines until "baseurl:"
  Helping you communicate a great experience.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: smutchings
github_username:  smutchings
permalink: /thought/:year/:month/:day/:title/

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /project/:path/